# -*- coding: utf-8 -*-
"""Object Detection Helmet YOLO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ig89Mn6AhaF1Bp4ruIcgW5jIAlD9dp2G
"""

!pip install -q ultralytics
import os
import zipfile
from ultralytics import YOLO

print(os.listdir('/content'))

zip_path = "/content/Helmet dataset - Kaggle and my own - Copy.zip"

print("Exists:", zipfile.os.path.exists(zip_path))
print("Is ZIP:", zipfile.is_zipfile(zip_path))

zip_path = "/content/Helmet dataset - Kaggle and my own - Copy.zip"

with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall("/content/dataset")

print("Dataset Extracted Successfully!")

print(os.listdir("/content/dataset"))

zip_path = "/content/Helmet dataset - Kaggle and my own - Copy.zip"

with zipfile.ZipFile(zip_path, 'r') as z:
    print("Number of files:", len(z.namelist()))
    print("\nFirst 20 entries:")
    for f in z.namelist()[:20]:
        print(f)

with open("/content/dataset/data.yaml", "r") as f:
    print(f.read())

model = YOLO("yolov8n.pt")

model.train(
    data="/content/dataset/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    project="helmet_detection",
    name="final_helmet_model"
)

#model evaluation
model = YOLO("/content/runs/detect/helmet_detection/final_helmet_model/weights/best.pt")

metrics = model.val()

print(metrics.results_dict)

#real time inference


model = YOLO("/content/runs/detect/helmet_detection/final_helmet_model/weights/best.pt")

results = model("/content/OIP.jpg", save=True)

#real time inference


model = YOLO("/content/runs/detect/helmet_detection/final_helmet_model/weights/best.pt")

model.predict(
    source="/content/AdobeStock_525843714.mov",
    save=True,
    conf=0.25
)

print(os.listdir("/content/runs/detect/predict-2"))