# -*- coding: utf-8 -*-
"""Plant Disease Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RFGuC1HXZOG67XVmQgDWcADbJ75HCKsR
"""

from google.colab import drive
import os
import zipfile
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import seaborn as sns
from google.colab import files

drive.mount('/content/drive')

dataset_path = "/content/drive/MyDrive"

print(os.listdir(dataset_path))

dataset_path = "/content/drive/MyDrive/plant dataset"

print(os.listdir(dataset_path)[:10])

zip_path = "/content/drive/MyDrive/plant village dataset.zip"
extract_path = "/content/plant_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

print(os.listdir("/content/plant_dataset"))

print(os.listdir("/content/plant_dataset/plantvillage dataset")[:20])

color_path = "/content/plant_dataset/plantvillage dataset/color"

print(os.listdir(color_path)[:10])

color_path = "/content/plant_dataset/plantvillage dataset/color"

train_ds = tf.keras.utils.image_dataset_from_directory(
    color_path,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=(128, 128),
    batch_size=32
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    color_path,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=(128, 128),
    batch_size=32
)

for images, labels in train_ds.take(1):
    print("Images Shape:", images.shape)
    print("Labels Shape:", labels.shape)
    print("First 10 Labels:", labels[:10].numpy())

print("Number of classes:", len(train_ds.class_names))
print(train_ds.class_names[:10])

plt.figure(figsize=(10,10))

for images, labels in train_ds.take(1):
    for i in range(9):
        ax = plt.subplot(3,3,i+1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(train_ds.class_names[labels[i]])
        plt.axis("off")

plt.show()

model = models.Sequential([

    # Normalize pixel values from 0-255 to 0-1
    layers.Rescaling(1./255, input_shape=(128, 128, 3)),

    # First Convolution Block
    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    # Second Convolution Block
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    # Third Convolution Block
    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    # Convert feature maps into a single vector
    layers.Flatten(),

    # Dense Layer
    layers.Dense(128, activation='relu'),

    # Output Layer (38 classes)
    layers.Dense(38, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

# Accuracy
plt.figure(figsize=(8,5))
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Training vs Validation Accuracy')
plt.show()

# Loss
plt.figure(figsize=(8,5))
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('Training vs Validation Loss')
plt.show()

loss, accuracy = model.evaluate(val_ds)

print("Validation Loss:", loss)
print("Validation Accuracy:", accuracy)

y_true = []
y_pred = []

for images, labels in val_ds:
    predictions = model.predict(images, verbose=0)

    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(predictions, axis=1))

cm = confusion_matrix(y_true, y_pred)

print(cm)

plt.figure(figsize=(12,10))

sns.heatmap(cm, cmap="Blues")

plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.show()

print(
    classification_report(
        y_true,
        y_pred,
        target_names=train_ds.class_names
    )
)

model.save("plant_disease_cnn.keras")

files.download("plant_disease_cnn.keras")